tunnel: 3ef51c08-231a-4785-9135-a402f8f0f6ca
credentials-file: /home/jan/.cloudflared/3ef51c08-231a-4785-9135-a402f8f0f6ca.json
protocol: http2

ingress:
  - hostname: training-planner.darwin-labs.org
    service: http://localhost:3000
  - hostname: flashcards.darwin-labs.org
    service: http://localhost:5000
  - hostname: usc-crawler.darwin-labs.org
    service: http://localhost:8501
  - hostname: ghost.darwin-labs.org
    service: http://localhost:2368
  - hostname: kcal-tracker.darwin-labs.org
    service: http://localhost:8787
  - hostname: n8n.darwin-labs.org
    service: http://localhost:5678
  - hostname: tunnel.darwin-labs.org
    service: ssh://localhost:22
  - service: http_status:404
